using Android.App;
using Android.Content;
using ServerStatusBot.Definitions;
using ServerStatusBot.Definitions.Api;
using ServerStatusBot.Definitions.Database.Models;
using ServerStatusBot.Definitions.Models;

namespace YouTubeHelper.Mobile.Platforms.Android
{
    [BroadcastReceiver(Enabled = true, Exported = true)]
    [IntentFilter(new[] { "com.micahmo.youtubehelper.NOTIFICATION_ACTION" })]
    public class NotificationActionReceiver : BroadcastReceiver
    {
        public override void OnReceive(Context? context, Intent? intent)
        {
            if (context is null || intent is null)
            {
                return;
            }

            string? rawUrl = intent.GetStringExtra(Intent.ExtraText);
            string? actionType = intent.GetStringExtra("actionType");
            string? markVideoStr = intent.GetStringExtra("markVideo");
            ExclusionReason? markVideoEnum = markVideoStr is { } s && Enum.TryParse(s, ignoreCase: true, out ExclusionReason reason) ? reason : null;
            bool downloadVideo = intent.GetBooleanExtra("downloadVideo", false);

            switch (actionType)
            {
                case "dismiss":
                    HandleDismiss(context, intent);
                    break;
            }

            if (!string.IsNullOrEmpty(rawUrl) && YouTubeUtils.GetVideoIdFromUrl(rawUrl) is { } videoId && markVideoEnum is not null)
            {
                // Immediately update notification to show the action as disabled
                string disabledAction = markVideoEnum.Value.ToString();
                UpdateNotificationWithDisabledAction(context, intent, disabledAction);

                PendingResult? pendingResult = GoAsync();

                _ = Task.Run(async () =>
                {
                    try
                    {
                        bool success = false;
                        try
                        {
                            if (await AppShell.ConnectToServerSilent())
                            {
                                if ((await ServerApiClient.Instance.FindVideos(new FindVideosRequest
                                {
                                    ExclusionsMode = ExclusionsMode.ShowAll,
                                    VideoIds = [videoId],
                                    SortMode = SortMode.AgeDesc,
                                    Count = int.MaxValue
                                })).FirstOrDefault() is { } video)
                                {
                                    video.Excluded = true;
                                    video.ExclusionReason = markVideoEnum.Value;

                                    // Since this update is generated by a notification, we DO want it to come back to ourselves in the app.
                                    // So use a blank client ID so we don't filter the message.
                                    video = await ServerApiClient.Instance.UpdateVideo(video, Guid.Empty.ToString());

                                    if (video.Excluded && video.ExclusionReason == markVideoEnum.Value)
                                    {
                                        success = true;
                                    }
                                }
                            }
                        }
                        catch
                        {
                            // Don't die due to any server problems; we still want to update the notification
                        }

                        // Wait a bit for the notification update to be visible, then dismiss
                        await Task.Delay(800);

                        if (success)
                        {
                            HandleDismiss(context, intent);
                        }
                        else
                        {
                            // Re-show the original notification
                            UpdateNotificationWithDisabledAction(context, intent, null);
                        }
                    }
                    finally
                    {
                        pendingResult?.Finish();
                    }
                });
            }

            if (!string.IsNullOrEmpty(rawUrl) && YouTubeUtils.GetVideoIdFromUrl(rawUrl) is { } videoId2 && downloadVideo)
            {
                // Immediately update notification to show the Download action as disabled
                UpdateNotificationWithDisabledAction(context, intent, "Download");

                PendingResult? pendingResult = GoAsync();

                _ = Task.Run(async () =>
                {
                    try
                    {
                        if (await AppShell.ConnectToServerSilent())
                        {
                            if ((await ServerApiClient.Instance.FindVideos(new FindVideosRequest
                            {
                                ExclusionsMode = ExclusionsMode.ShowAll,
                                VideoIds = [videoId2],
                                SortMode = SortMode.AgeDesc,
                                Count = int.MaxValue
                            })).FirstOrDefault() is { } video)
                            {
                                await ServerApiClient.Instance.DownloadVideo(
                                    url: rawUrl,
                                    silent: true,
                                    requestId: Guid.NewGuid().ToString(),
                                    dataDirectorySubpath: "plex",
                                    videoId: video.Id,
                                    videoName: video.Title ?? string.Empty,
                                    thumbnailUrl: video.ThumbnailUrl ?? string.Empty,
                                    channelThumbnailUrl: video.ChannelThumbnailUrl,
                                    channelPlaylist: video.ChannelPlaylist,
                                    channelName: video.ChannelName,
                                    idInChannelFolder: true);
                            }
                        }
                    }
                    finally
                    {
                        pendingResult?.Finish();
                    }
                });
            }
        }

        private void UpdateNotificationWithDisabledAction(Context context, Intent intent, string? disabledAction)
        {
            // Extract all the data needed to rebuild the notification
            int notificationId = intent.GetIntExtra("notificationId", -1);
            string title = intent.GetStringExtra("title") ?? string.Empty;
            string body = intent.GetStringExtra("body") ?? string.Empty;
            string videoUrl = intent.GetStringExtra(Intent.ExtraText) ?? string.Empty;
            string thumbnailPath = intent.GetStringExtra("thumbnailPath") ?? string.Empty;
            string channelThumbnailPath = intent.GetStringExtra("channelThumbnailPath") ?? string.Empty;
            string channelId = intent.GetStringExtra("channelId") ?? string.Empty;
            bool isDone = intent.GetBooleanExtra("isDone", false);
            bool isNewVideo = intent.GetBooleanExtra("isNewVideo", false);
            bool isFailed = intent.GetBooleanExtra("isFailed", false);
            bool hasProgress = intent.GetBooleanExtra("hasProgress", false);
            double progress = intent.GetDoubleExtra("progress", 0);
            string? plexRatingKey = intent.GetStringExtra("plexRatingKey");
            string? channelName = intent.GetStringExtra("channelName");

            // Call the Show method with the disabled action parameter
            AndroidNotificationHelper.Show(
                title: title,
                channelName: channelName,
                body: body,
                videoUrl: videoUrl,
                thumbnailPath: thumbnailPath,
                channelThumbnailPath: channelThumbnailPath,
                notificationChannelId: channelId,
                notificationId: notificationId,
                isDone: isDone,
                isNewVideo: isNewVideo,
                isFailed: isFailed,
                hasProgress: hasProgress,
                progress: progress,
                plexRatingKey: plexRatingKey,
                disabledAction: disabledAction
            );
        }

        private void HandleDismiss(Context context, Intent intent)
        {
            int notificationId = intent.GetIntExtra("notificationId", -1);
            AndroidX.Core.App.NotificationManagerCompat.From(context).Cancel(notificationId);
        }
    }
}
