//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouTubeHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YouTubeHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active downloads: {0}.
        /// </summary>
        public static string ActiveDownloads {
            get {
                return ResourceManager.GetString("ActiveDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter video IDs (one per line) to mark as Might Watch for channel &apos;{0}&apos; ({1}).
        /// </summary>
        public static string AddMightWatchIdsMessage {
            get {
                return ResourceManager.GetString("AddMightWatchIdsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter video IDs (one per line) to mark as Watched for channel &apos;{0}&apos; ({1}).
        /// </summary>
        public static string AddWatchedIdsMessage {
            get {
                return ResourceManager.GetString("AddWatchedIdsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter video IDs (one per line) to mark as Won&apos;t Watch for channel &apos;{0}&apos; ({1}).
        /// </summary>
        public static string AddWontWatchIdsMessage {
            get {
                return ResourceManager.GetString("AddWontWatchIdsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTubeHelper.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel name.
        /// </summary>
        public static string ChannelName {
            get {
                return ResourceManager.GetString("ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count: {0}.
        /// </summary>
        public static string CountLabel {
            get {
                return ResourceManager.GetString("CountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current download directory: {0}.
        /// </summary>
        public static string CurrentDownloadDirectory {
            get {
                return ResourceManager.GetString("CurrentDownloadDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date range limit.
        /// </summary>
        public static string DateRangeLimit {
            get {
                return ResourceManager.GetString("DateRangeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show videos before.
        /// </summary>
        public static string DoNotShowVideosBefore {
            get {
                return ResourceManager.GetString("DoNotShowVideosBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show videos shorter than.
        /// </summary>
        public static string DoNotShowVideosShorterThan {
            get {
                return ResourceManager.GetString("DoNotShowVideosShorterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download (hold Shift to download silently, right-click to specify download directory).
        /// </summary>
        public static string DownloadButtonToolTip {
            get {
                return ResourceManager.GetString("DownloadButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the download directory to use..
        /// </summary>
        public static string DownloadDirectoryMessage {
            get {
                return ResourceManager.GetString("DownloadDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Directory.
        /// </summary>
        public static string DownloadDirectoryTitle {
            get {
                return ResourceManager.GetString("DownloadDirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading...  {0}.
        /// </summary>
        public static string DownloadingProgress {
            get {
                return ResourceManager.GetString("DownloadingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a MongoDB connection string..
        /// </summary>
        public static string EnterConnectionString {
            get {
                return ResourceManager.GetString("EnterConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error connecting to the database.
        ///
        ///{0}.
        /// </summary>
        public static string ErrorConnectingToDatabase {
            get {
                return ResourceManager.GetString("ErrorConnectingToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error processing your request. Please try again..
        /// </summary>
        public static string ErrorProcessingRequest {
            get {
                return ResourceManager.GetString("ErrorProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact search.
        /// </summary>
        public static string ExactSearch {
            get {
                return ResourceManager.GetString("ExactSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCLUDED.
        /// </summary>
        public static string Excluded {
            get {
                return ResourceManager.GetString("Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusions.
        /// </summary>
        public static string Exclusions {
            get {
                return ResourceManager.GetString("Exclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup.
        /// </summary>
        public static string Lookup {
            get {
                return ResourceManager.GetString("Lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Might Watch.
        /// </summary>
        public static string MarkAsMightWatch {
            get {
                return ResourceManager.GetString("MarkAsMightWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Watched.
        /// </summary>
        public static string MarkAsWatched {
            get {
                return ResourceManager.GetString("MarkAsWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Won&apos;t Watch.
        /// </summary>
        public static string MarkAsWontWatch {
            get {
                return ResourceManager.GetString("MarkAsWontWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked {0} new video(s) as Might Watch.
        ///Updated the status of {1} video(s)..
        /// </summary>
        public static string MarkedAsMightWatch {
            get {
                return ResourceManager.GetString("MarkedAsMightWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked {0} new video(s) as Watched.
        ///Updated the status of {1} video(s)..
        /// </summary>
        public static string MarkedAsWatched {
            get {
                return ResourceManager.GetString("MarkedAsWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked {0} new video(s) as Won&apos;t Watch.
        ///Updated the status of {1} video(s)..
        /// </summary>
        public static string MarkedAsWontWatch {
            get {
                return ResourceManager.GetString("MarkedAsWontWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Might watch.
        /// </summary>
        public static string MightWatch {
            get {
                return ResourceManager.GetString("MightWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Channel.
        /// </summary>
        public static string NewChannel {
            get {
                return ResourceManager.GetString("NewChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶.
        /// </summary>
        public static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show excluded videos.
        /// </summary>
        public static string ShowExcludedVideos {
            get {
                return ResourceManager.GetString("ShowExcludedVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MMMM d, yyyy}  •  {1} day(s) ago  •  {2}.
        /// </summary>
        public static string TimeStringFormat {
            get {
                return ResourceManager.GetString("TimeStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application encountered an unexpected error..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download &apos;{0}&apos;.
        ///
        ///{1}.
        /// </summary>
        public static string VideoDownloadFailed {
            get {
                return ResourceManager.GetString("VideoDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent request to download &apos;{0}&apos;..
        /// </summary>
        public static string VideoDownloadRequested {
            get {
                return ResourceManager.GetString("VideoDownloadRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully downloaded &apos;{0}&apos;..
        /// </summary>
        public static string VideoDownloadSucceeded {
            get {
                return ResourceManager.GetString("VideoDownloadSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video length minimum (in seconds).
        /// </summary>
        public static string VideoLengthMinimum {
            get {
                return ResourceManager.GetString("VideoLengthMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        public static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched.
        /// </summary>
        public static string Watched {
            get {
                return ResourceManager.GetString("Watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won&apos;t watch.
        /// </summary>
        public static string WontWatch {
            get {
                return ResourceManager.GetString("WontWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
