//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouTubeHelper.Mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YouTubeHelper.Mobile.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Downloads.
        /// </summary>
        internal static string ActiveDownloads {
            get {
                return ResourceManager.GetString("ActiveDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} download(s) in progress..
        /// </summary>
        internal static string ActiveDownloadsText {
            get {
                return ResourceManager.GetString("ActiveDownloadsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the app before sharing..
        /// </summary>
        internal static string CloseAppBeforeShare {
            get {
                return ResourceManager.GetString("CloseAppBeforeShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to database....
        /// </summary>
        internal static string ConnectingToDatabase {
            get {
                return ResourceManager.GetString("ConnectingToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download (custom path)....
        /// </summary>
        internal static string DownloadCustom {
            get {
                return ResourceManager.GetString("DownloadCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the download directory to use..
        /// </summary>
        internal static string DownloadDirectoryMessage {
            get {
                return ResourceManager.GetString("DownloadDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Directory.
        /// </summary>
        internal static string DownloadDirectoryTitle {
            get {
                return ResourceManager.GetString("DownloadDirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading...  {0}.
        /// </summary>
        internal static string DownloadingProgress {
            get {
                return ResourceManager.GetString("DownloadingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download ({0}).
        /// </summary>
        internal static string DownloadPath {
            get {
                return ResourceManager.GetString("DownloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a MongoDB connection string..
        /// </summary>
        internal static string EnterConnectionString {
            get {
                return ResourceManager.GetString("EnterConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the desired limit:.
        /// </summary>
        internal static string EnterDesiredLimit {
            get {
                return ResourceManager.GetString("EnterDesiredLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a numerical limit..
        /// </summary>
        internal static string EnterNumericalLimit {
            get {
                return ResourceManager.GetString("EnterNumericalLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error connecting to the database: {0}.
        /// </summary>
        internal static string ErrorConnectingToDatabase {
            get {
                return ResourceManager.GetString("ErrorConnectingToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error processing your request. Please try again..
        /// </summary>
        internal static string ErrorProcessingRequest {
            get {
                return ResourceManager.GetString("ErrorProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error processing your request. Please try again.
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorProcessingRequestMessage {
            get {
                return ResourceManager.GetString("ErrorProcessingRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude: Might Watch.
        /// </summary>
        internal static string ExcludeMightWatch {
            get {
                return ResourceManager.GetString("ExcludeMightWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude: Watched.
        /// </summary>
        internal static string ExcludeWatched {
            get {
                return ResourceManager.GetString("ExcludeWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude: Won&apos;t Watch.
        /// </summary>
        internal static string ExcludeWontWatch {
            get {
                return ResourceManager.GetString("ExcludeWontWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Download.
        /// </summary>
        internal static string FailedToDownload {
            get {
                return ResourceManager.GetString("FailedToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading channels....
        /// </summary>
        internal static string LoadingChannels {
            get {
                return ResourceManager.GetString("LoadingChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        internal static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search ({0}).
        /// </summary>
        internal static string SearchCount {
            get {
                return ResourceManager.GetString("SearchCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search history.
        /// </summary>
        internal static string SearchHistory {
            get {
                return ResourceManager.GetString("SearchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search history (none).
        /// </summary>
        internal static string SearchHistoryNone {
            get {
                return ResourceManager.GetString("SearchHistoryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search limit.
        /// </summary>
        internal static string SearchLimit {
            get {
                return ResourceManager.GetString("SearchLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (no limit).
        /// </summary>
        internal static string SearchNoLimit {
            get {
                return ResourceManager.GetString("SearchNoLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with limit.
        /// </summary>
        internal static string SearchWithLimit {
            get {
                return ResourceManager.GetString("SearchWithLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexclude.
        /// </summary>
        internal static string Unexclude {
            get {
                return ResourceManager.GetString("Unexclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download &apos;{0}&apos;.
        ///
        ///{1}.
        /// </summary>
        internal static string VideoDownloadFailed {
            get {
                return ResourceManager.GetString("VideoDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent request to download &apos;{0}&apos;..
        /// </summary>
        internal static string VideoDownloadRequested {
            get {
                return ResourceManager.GetString("VideoDownloadRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully downloaded &apos;{0}&apos;..
        /// </summary>
        internal static string VideoDownloadSucceeded {
            get {
                return ResourceManager.GetString("VideoDownloadSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        internal static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch (external).
        /// </summary>
        internal static string WatchExternal {
            get {
                return ResourceManager.GetString("WatchExternal", resourceCulture);
            }
        }
    }
}
